### ISSUE TITLE
Enhancements to `quantum_info.expressibility`

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1050]
By using this function I have noticed an exponential scaling in runtime with $n$ and $t$.
Here are several improvements to its auxiliary functions that can reduce runtime significantly:

- `random_statevector` needs a way to sample Haar-random states without resorting to selecting an uniformly random column of a Haar-random unitary.
- `haar_integral` does not have to always be computed via sampling. Since this integral is the $t$-th momentum operator of Haar-random states, it can be calculated exactly (see Lemma 39 of [Ingo's tutorial on benchmarking](https://journals.aps.org/prxquantum/pdf/10.1103/PRXQuantum.2.010201)). This should improve performance for small $n$, but be worse than the sampling method for bigger $n$. This is due to the fact that the number of terms that have to be summed up for the exact calculation grows as a factorial in $t$. For this reason, I think we should have both methods implemented, with default being exact.

My next point is more of a logical bug than an enhancement:
- if I understood correctly, `pqc_integral` is now calculating an integral over parametrized circuits by sampling all rotation phases over an uniform distribution in the interval $[-\pi, \pi]$. That's wrong. In my opinion, this should be an user input that, if `None`, defaults to sampling over an uniform distribution over the Bloch sphere. An uniform distribution of the phases is a biased distribution over the Bloch sphere.

```[tasklist]
### Tasks
- [ ] https://github.com/qiboteam/qibo/pull/1052
- [ ] https://github.com/qiboteam/qibo/pull/1057
```

**Comment by renatomello** [comment]
What do you think @AlejandroSopena ?

**Comment by AlejandroSopena** [comment]
I agree with the first two comments. I was aware of the expression of the $t$-momentum operator for Haar random states in terms of the projector onto the symmetric subspace. I implemented it through sampling (without really considering the scaling) because it seemed easier for coding but it would be good to have the exact method,

Regarding the `pcq_integral`, it is typically calculated over the ensemble of states generated by randomly sampling the parameter space (see [Zoë (expressibility and BP)](https://arxiv.org/abs/2101.02138) and [expressibility and entanglement](https://arxiv.org/abs/1905.10876)) It might be useful to introduce other distributions and the option to sample from the single qubit Haar measure for completeness.

I can take care of these improvements.

**Comment by renatomello** [comment]
Thanks @AlejandroSopena.

Regarding the literature, let me ask you a question since you're more familiar with it: how do people square the idea of sampling uniformly over the parameters with that fact that this procedure does not lead to a uniform sampling over the states the circuit can create?
