### ISSUE TITLE
Higher order product formulas for double bracket rotations in the dbi model

### ISSUE THREAD

**Issue by Tellememe** [qiboteam/qibo#1341]
### Higher Order Product Formula for DBR in the DBI Model

The third order product formula is given by:
$S_3 := e^{x\hat{A}\frac{\sqrt{5}-1}{2}}e^{x\hat{B}\frac{\sqrt{5}-1}{2}}e^{-x\hat{A}}e^{ -x\hat{B}\frac{\sqrt{5}+1}{2}}e^{x\hat{A}\frac{3-\sqrt{5}}{2}}e^{x\hat{B}} = e^{x^2[\hat{A},\hat{B}]} + \mathcal{O}(x^4)$ 

where $\hat{A}$ and $\hat{B}$ are arbitrary Hermitian operators. 

In the context of DBI, we previously implemented the following second-order product formula which we call GCI:

$S_2 := S_{2}(x):=e^{x \hat{A}} e^{x \hat{B}} e^{-x\hat{A}} e^{-x \hat{B}}=e^{x^{2}[\hat{A}, \hat{B}]}+O\left(x^{3}\right) $

**Diagonalization Routine for GCI algorithm**

**Input**

1. $\hat{H}_0$: Initial Hamiltonian
2. $\hat{D}$: Diagonal association (canonical or BHMM operator)
3. $s$: flow duration for a single recursion step $k$
4. $K$: Total number of recursion steps

**Output**
$\hat{H}_K$: Final (diagonalized) Hamiltonian

**Procedure**

1. For $k\in[0,K)$, use the reduced group commutator $\hat{U}_k \leftarrow e^{i\sqrt{s_k}\hat{D}_k}e^{i\sqrt{s_k}\hat{H}_k}e^{-i\sqrt{s_k}\hat{D}_k}$
2. $\hat{H}_{k+1} \leftarrow \hat{U^{\dagger}}_k\hat{H}_k\hat{U}_k$
3. Repeat steps 1 to 4 for the next recursion step

Below, I have attached my Jupyter Notebook files in which I studied the higher-order product formula (notably, the 3rd-order product formula) implementation in the DBI algorithm: 

**1. Multiple DBR steps for product formula orders 2 and 3.** 

[DBR _higher_order_PF.pdf](https://github.com/user-attachments/files/15538427/DBR._higher_order_PF.pdf)

**2. Error scale plots for product formula orders 2 and 3.** 
[Error Scale.pdf](https://github.com/user-attachments/files/15538667/Error.Scale.pdf)

**3. DBI implementation for order 3.**
[DBI _higher_order_PF-copy.pdf](https://github.com/user-attachments/files/15538981/DBI._higher_order_PF-copy.pdf)

If there are any discrepancies between my typed equations and the manuscript, do let me know. 

~Ashwinie

**Comment by marekgluza** [comment]
Hi @Tellememe thanks for adding. @wrightjandrew cf the updated issue content for your #1342 

Ashwinie can you next 

- [ ] comment below and derive the symmetry relations for the second order by setting $A=\pm iH, B=\pm iD$ or $A=\pm iD, iB=\pm H$, generalize the 1st order https://mathstodon.xyz/@Marekgluza/112279346010080479
- [ ] Please add the derivations including the transitions which include $i^2=-1$ (I made mistakes because of that a few times) what happens if the operators are exchanged and what is being approximated
- [ ] Finally we want to rotate $S_3^\dagger A S_3$ so please reduce the formula and propose a worked out formula analogous to #1342 for an implementation
- [ ] previous point either @Tellememe or @wrightjandrew will implement in a seperate pull request
- [ ] Ashwinie, once the derivations are settled here for the future reference, you will be tasked with providing documentation. That will be roughly copy paste of what will be here.

**Comment by marekgluza** [comment]
https://arxiv.org/pdf/2111.12177 the $S_3$ above comes from this paper
