### ISSUE TITLE
Retrieve nested samples during `MeasurementOutcome` dump

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#1426]
I am trying to dump the circuit results object and reload. 
The qibolab backend is not storing samples therefore the code crashes.

Code example using the latest `module load qibo` and `sbatch -p qw5q_platinum`):
```python
import qibo
c = qibo.Circuit(5)
c.add(qibo.gates.M(0))
r = c(nshots=100)
r.dump("./output.npy")
```
Then, while loading:
```python
import qibo
qibo.result.load_result("output.npy").samples()
```
we get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/users/test.test/qibo/src/qibo/result.py", line 341, in samples
    samples = self.backend.sample_shots(self._probs, self.nshots)
  File "/nfs/users/test.test/qibo/src/qibo/backends/numpy.py", line 650, in sample_shots
    range(len(probabilities)), size=nshots, p=probabilities
TypeError: object of type 'NoneType' has no len()
```

**Comment by scarrazza** [comment]
@BrunoLiegiBastonLiegi may I ask you to have a look at this?

**Comment by alecandido** [comment]
Sorry @scarrazza to have stopped here: I actually started implementing, but then the proposed solution didn't seem that good.

The `MeasurementOutcome.to_dict()` method was meant to serialize the object, in a way that it could be recreated.
For this reason, is also serializing the gates:
https://github.com/qiboteam/qibo/blob/386fe25c69e54211b4816702b5f0b619d645b35c/src/qibo/result.py#L417

However, the `M` gate is not customizing the `.raw` property (and thus `.to_json()` method), relying on the general `Gate` behavior, which is only retaining the arguments needed to construct:
https://github.com/qiboteam/qibo/blob/386fe25c69e54211b4816702b5f0b619d645b35c/src/qibo/gates/abstract.py#L75-L89
(you can read the list of the selected arguments in the `REQUIRED_*` constants on top) skipping the `M.result` attribute
https://github.com/qiboteam/qibo/blob/386fe25c69e54211b4816702b5f0b619d645b35c/src/qibo/gates/measurements.py#L59

But on its turn, `MeasurementResult` has no available way to be serialized (which it could be defined).

The `._samples` to `.samples()` above is a bit destructive, because the object reloaded would not be the exact same (you will get the samples separately from the gate, and the gate would still be empty, though there).
Thus, I started thinking to fix in the way above, but I stopped because I had to write the `MeasurementResult`.

If @BrunoLiegiBastonLiegi can take a look, I'm pretty sure it's a pretty straight issue, but it might take a bit of time defining a proper serialization for `MeasurementResult` (since it has many attributes, but some may be computed, as generated by its methods, so not worth to serialize).
