### ISSUE TITLE
Refactoring of `models.encodings`

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1506]
By looking at the latest `GHZ` PR #1496 and the `qiboml` implementations, I'd like to propose changing the functions in `models.encodings` to classes that inherit the `Circuit` class. It seems like a more fitting approach and easier to integrate with both the `tomography` module in `qibo` as well as the new model classes in `qiboml`.

Of course, some time for deprecation should be allowed.

**Comment by alecandido** [comment]
I'm a bit doubtful...

I've seen the encodings in `qiboml` as a potential duplication, and tried to convince to keep them as `Circuit`s-generating functions (following the Qibo approach), because adding layers on top of the `Circuit` seem to me that was increasing complexity, but I was not able to see any advantage.

`Circuit` can be stacked, and they can be applied on certain qubits, which is usually all you need to compose smaller `Circuit`s into larger algorithms.
If something is missing, we may even consider upgrading the `Circuit` class itself.

But, most likely, I'm just missing the point. Could you elaborate about the advantage that would be provided by a class?

**Comment by renatomello** [comment]
> I'm a bit doubtful...
> 
> I've seen the encodings in Qiboml as a potential duplication, and tried to convince to keep them as `Circuit`s-generating functions (following the Qibo approach), because adding layers on top of the `Circuit` seem to me that was increasing complexity, but I was not able to see any advantage.
> 
> `Circuit` can be stacked, and they can be applied on certain qubits, which is usually all you need to compose smaller `Circuit`s into larger algorithms. If something is missing, we may even consider upgrading the `Circuit` class itself.
> 
> But, most likely, I'm just missing the point. Could you elaborate about the advantage that would be provided by a subclass?
> 
> EDIT: since we're discussing the approach also used in Qiboml, maybe better to also tag @BrunoLiegiBastonLiegi

There is almost no difference when dealing with simpler encoders like the ones implemented right now, but it makes a difference for more complex circuits. For instance, even for the `unary_encoder` implemented right now, the helper functions necessary to generate those circuits could be (even static) methods of a `UnaryEncoder` class, and `UnaryEncoderRandomGaussian` could inherit those methods by having `UnaryEncoder` as a parent class. 
More complex encoders like [arXiv quant-ph/04071010](https://arxiv.org/abs/quant-ph/0407010), [arXiv 2405.20408](https://arxiv.org/abs/2405.20408), [arXiv 2309.15547](https://arxiv.org/abs/2309.15547) would also benefit from having their methods. I don't see these methods being so generic to the point of being part of the `raw` circuit implementation though.

**Comment by alecandido** [comment]
> In the end, using objects or not is a design choice.

Yes, I perfectly agree.

In general, classes are useful, because they group together functions with a state. Usually the functions are used to manipulate the state (this is explicitly not the case of static methods, for which the class is just a namespace, and nothing else).

However, for the same reason they are useful, they are also potentially harmful: a large-enough state resembles a global one (of which I could explain the downsides, but it's sufficiently renowned to be a bad practice), and in general you want to keep your computation as stateless as possible, to improve isolation and composition (and to make debugging easier, since you don't need to track a state around).

So, it's useful to keep a stateful `Circuit`, or a stateful random generator, because the alternatives are not very familiar to the user (cons and random sequence state propagation - cf. JAX, but in general that's a feature of functional languages). I'm not so purist to invoke complete classes removal.
But since classes come with a trade-off, I advise avoiding them whenever possible, and just use plain functions and their composition. That resembles the so-called [rule of least power](https://en.wikipedia.org/wiki/Rule_of_least_power).

If you need namespaces, modules already provide good enough ones (though it's true that Python is lacking internal ones, but I suggest you to proliferate files, since it has little downsides).

> I don't see these methods being so generic to the point of being part of the `raw` circuit implementation though.

Indeed, I would make part of it as well.

**Comment by renatomello** [comment]
> > In the end, using objects or not is a design choice.
> 
> Yes, I perfectly agree.
> 
> In general, classes are useful, because they group together functions with a state. Usually the functions are used to manipulate the state (this is explicitly not the case of static methods, for which the class is just a namespace, and nothing else).
> 
> However, for the same reason they are useful, they are also potentially harmful: a large-enough state resembles a global one (of which I could explain the downsides, but it's sufficiently renowned to be a bad practice), and in general you want to keep your computation as stateless as possible, to improve isolation and composition (and to make debugging easier, since you don't need to track a state around).
> 
> So, it's useful to keep a stateful `Circuit`, or a stateful random generator, because the alternatives are not very familiar to the user (cons and random sequence state propagation - cf. JAX, but in general that's a feature of functional languages). I'm not so purist to invoke complete classes removal. But since classes come with a trade-off, I advise avoiding them whenever possible, and just use plain functions and their composition. That resembles the so-called [rule of least power](https://en.wikipedia.org/wiki/Rule_of_least_power).
> 
> If you need namespaces, modules already provide good enough ones (though it's true that Python is lacking internal ones, but I suggest you to proliferate files, since it has little downsides).
> 
> > I don't see these methods being so generic to the point of being part of the `raw` circuit implementation though.
> 
> Indeed, I would make part of it as well.

I understand that argument. In the end, these classes would be Circuits with at most a handful of extra methods, so idk how much overhead that would be.

Also, I'd say that it is more intuitive to the user.

However, if it is not recommended, then we could just close this.

**Comment by renatomello** [comment]
I won't have time to move forward with this in the foreseeable future. Since it is not a big necessity, I'll this issue and the PR. If necessary, we can reopen it later on.
