### ISSUE TITLE
Core dumped for tests on GPU

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#361]
It looks like some tests, such as `test_entanglement_entropy` fail on GPUs with low memory (say ~4GB), with a core dumped crash.

The problem seems to come from tensorflow/cuda when calling the `tf.linalg.eigvalsh` method. Here a minimal example:

```python
import tensorflow as tf
rho = tf.constant([[ 9.14909492+1.14491749e-16j,  0.27933987-1.27970271e-01j, 
    0.25616772+1.12442776e-01j, -0.05876706-3.76165554e-01j],
    [ 0.27933987+1.27970271e-01j,  9.62506895+2.77555756e-17j,
    -0.19640032-1.72149754e-01j,  0.28515435+2.58716412e-01j],
    [ 0.25616772-1.12442776e-01j, -0.19640032+1.72149754e-01j,
    9.13383471-1.38777878e-17j,  0.18600413-2.68212068e-01j],
    [-0.05876706+3.76165554e-01j,  0.28515435-2.58716412e-01j,
    0.18600413+2.68212068e-01j,  9.58168325-5.20417043e-17j]])
tf.linalg.eigvalsh(rho)
```

while the same code with `eigvals` does not crash.

@stavros11 could you please try to reproduce this issue?

We can report that on TF, and would be great to try on the dgx by limiting the GPU memory.

**Comment by stavros11** [comment]
> @stavros11 could you please try to reproduce this issue?

I just tried on my notebook GPU (GTX 1650 4GB) and I have not issues executing the example. I tried with rho of size up to (2^13, 2^13) and the diagonalization works with no issues on GPU. Also Qibo tests pass, which is strange because yesterday I was also getting core dumped when I was running the tests.

**Comment by scarrazza** [comment]
Interesting, I can get rid of this issue by limiting the GPU memory...

**Comment by stavros11** [comment]
I had a look at the failing tests and can confirm that all failures when executing on GPU are due to the following methods:

* `tf.linalg.eigh`
* `tf.linalg.eigvalsh`
* `tf.linalg.expm`

Running the example from the first post on GPU gives core dumped for me as well now. I am not sure why everything was working yesterday... Also replacing `eigvalsh` with any of the methods listed above gives the same error. The error is fixed if I limit the GPU memory.

I guess we can report the problem on tf. We can also fix our tests on GPU by limiting the memory before execution. I tried doing it using:
```Python
**# Limit GPU memory
for gpu in tf.config.list_physical_devices("GPU"):
    config = tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024)
    tf.config.experimental.set_virtual_device_configuration(gpu, [config])
```
but I am not sure where to put it in the `conftest.py` so that it is called before any imports (I get `RuntimeError: Virtual devices cannot be modified after being initialized`).

**Comment by scarrazza** [comment]
@stavros11 great, could you please confirm that if you set this before running these functions solves the issue?
```python
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)
```

I would keep the code as it is for now, and wait for their feedback.

**Comment by stavros11** [comment]
> @stavros11 great, could you please confirm that if you set this before running these functions solves the issue?

Yes, I can confirm that limiting the GPU memory either with the code I wrote above or with `set_memory_growth` method you used solves the problem for all methods.

Also, note that sometimes the problem may not appear even without limiting the memory. I think it only appears when a minimum fraction of the GPU memory is used by other applications.

**Comment by scarrazza** [comment]
Ok, I will open an issue.

**Comment by scarrazza** [comment]
https://github.com/tensorflow/tensorflow/issues/48041

**Comment by scarrazza** [comment]
This issue seems fixed with tf2.5.0. and CUDA 11.2.
