### ISSUE TITLE
Computing hamiltonians expectation values with the custom backend

### ISSUE THREAD

**Issue by AdrianPerezSalinas** [qiboteam/qibo#413]
hi all, 

I am trying to compute the expectation value of some Fermi Hubbard hamiltonian where the terms are of this kind
```
1.0 [] +
-0.5 [X0 Z1 X2] +
-0.5 [X0 Z1 Z2 Z3 X4] +
-0.5 [Y0 Z1 Y2] +
-0.5 [Y0 Z1 Z2 Z3 Y4] +
-0.25 [Z0] + ...
```

If I do it with custom backend, I obtain the error message
```
[Qibo|ERROR|2021-05-20 16:26:50]: Unitary gate supports one or two-qubit gates when using custom operators, but 3 target qubits were given. Please switch to a different backend to execute this operation.

NotImplementedError: Unitary gate supports one or two-qubit gates when using custom operators, but 3 target qubits were given. Please switch to a different backend to execute this operation.
```

Does it behave as expected? Should we consider implement it for custom backend?

**Comment by stavros11** [comment]
> Does it behave as expected?

I think yes, because custom operators contain kernels for up to two qubit gates. The trotterization procedure that is coded in qibo just splits the Hamiltonian terms but does not reduce the target qubits of each term, so for example the `[Y0 Z1 Y2]` will be mapped to a three qubit `Unitary` gate which cannot be applied using the qibotf backend. It should work with numpy and tensorflow though but ofcourse will be slower.

> Should we consider implement it for custom backend?

Regarding implementing this, there are probably two ways:
1. Reduce the >2 qubit terms to two qubit gates. This can be done exactly since two qubit gate sets are universal but we do not have any compilation algorithm in qibo to do this automatically yet. Also there may be a performance tradeoff between doing it exactly but slow, or approximately but faster that we may want to consider if we try to implement this approach.
2. Write kernels for >2 qubit gates. The main issue with this solution is that it doesn't scale, for example we can write up to four qubit kernels to accomodate the terms you wrote, but then we won't be able to accomodate a five qubit term, etc.. The reason the custom kernels were up to two qubit is that these are the gates that are more relevant for hardware.

**Comment by scarrazza** [comment]
@AdrianPerezSalinas could you please measure the execution time for your code using the latest master (0.1.6-dev) with `set_backend("numpy")` and `set_backend("tensorflow")`?

**Comment by scarrazza** [comment]
@AdrianPerezSalinas thanks for this numbers.

**Comment by AdrianPerezSalinas** [comment]
I can also upload the .py file for these numbers
[benchmark_qibo.txt](https://github.com/qiboteam/qibo/files/6553856/benchmark_qibo.txt)

**Comment by stavros11** [comment]
After some more careful thinking I would like to correct my above post: What I wrote is valid when the Hamiltonian is used for time evolution. In this case we need to apply exp(-i dt H) to the state which after Trotterization will give terms of the form exp(-i dt Y0 Z1 Z2 Z3 Y4) which are indeed four qubit gates and require special kernels.

However, when it comes to expectation values which are the topic of this issue, a four qubit kernel is NOT required. We only need to compute terms like <Psi | Y0 Z1 Z2 Z3 Y4 | Psi > which can be calculated using only one qubit gates. I will have a second look on how the `TrotterHamiltonian.expectation` method is implemented because I think we can simplify it and make it work with qibotf without the need of additional kernels.
