### ISSUE TITLE
U1.matrix returns a single value

### ISSUE THREAD

**Issue by igres26** [qiboteam/qibo#444]
When trying to get the matrix form of U1, qibo returns a single value of the exponential instead of the full 2x2 matrix.

**Comment by stavros11** [comment]
Thanks for reporting this. Indeed when using the qibojit or qibotf backends
```Python
g = gates.U1(0, theta=0.1)
g.matrix
```
will give only the value of the exponential instead of the full matrix, while `g.unitary` will give the full matrix you expect. There are similar discrepancies for other gates such as the fSim.

This is because `.matrix` gives the numbers that are required by the corresponding custom operator, while `.unitary` always gives the full matrix representation in the computational basis. For U1 the custom operator requires only the phase because it works with indexing:
```Python
state[i] *= phase
```
for all appropriate `i`.

So the short answer would be that if you use `U1.unitary` instead of `.matrix` you should get the correct matrices for all gates. However if @scarrazza agrees perhaps we should change `U1.matrix` to be equivalent to `U1.unitary`, or just remove one of the two and use a different name not accessible by user (eg. `U1._matrix`) for internal custom operator manipulations.

**Comment by scarrazza** [comment]
@stavros11 yes, I agree. We can probably replace `.unitary` with `.unitary_matrix` and `.matrix` with `._matrix`, and document these changes in the docs.

**Comment by igres26** [comment]
Thanks for the quick response. It is a bit misleading that asking for a matrix returns something that's not a matrix. So merging both seems reasonable.
