### ISSUE TITLE
Flag "is_executed" is defined but not implemented

### ISSUE THREAD

**Issue by mlazzarin** [qiboteam/qibo#462]
The "is_executed" flag in the AbstractCircuit class is defined here
https://github.com/qiboteam/qibo/blob/14bb45448209312e68df8176647e796a74109f71/src/qibo/abstractions/circuit.py#L91-L93
but it seems like it is not accessed nor modified anywhere in the source code of Qibo.
Indeed, it always returns False. The "add" method ignores it and simply checks for "_final_state"
https://github.com/qiboteam/qibo/blob/4073ce9d96836cb46c1abf2e2b75b7270c0331d4/src/qibo/abstractions/circuit.py#L390-L392
This is a minor bug but it may cause issues if such flag is used by unaware users.
Should we implement it properly (or simply remove it)?

**Comment by scarrazza** [comment]
@mlazzarin thanks for pointing this out.  I think we forgot to remove this attribute after some cleanup, nowadays we check this features in https://github.com/qiboteam/qibo/blob/14bb45448209312e68df8176647e796a74109f71/src/qibo/abstractions/circuit.py#L390-L392

@stavros11 do you agree, right?

**Comment by stavros11** [comment]
@mlazzarin thank you for checking the code. Indeed you may find some attributes around the code that are not used anymore because we forgot to remove them during a cleanup or refactoring. This particular attribute seems redundant to me as any `if self.is_executed` could be replaced by `if self._final_state is not None` since, if I am not mistaken, the final state attribute is assigned after a circuit execution.

I don't think such attributes would cause problems in every day usage but may confuse people that look at the code and should be removed. @mlazzarin you can remove this if you like.
