### ISSUE TITLE
sympy vs qibo symbols performance

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#469]
We should verify the impact of the `expand` call in qibo.
It looks like this call deteriorates our performance in comparison to a pure sympy implementation.

**Comment by stavros11** [comment]
Some information that I believe is relevant: I tried constructing a simple Hamiltonian for which the `sympy.expand` call is still non-trivial so that there is a difference between qibo and pure sympy symbols. The example I used is the following:
```
h = (1 - Z1)**6 (1 - Z2)**6 ... (1 - Zn)**6
```
where `n` is the number of qubits. This is a diagonal Hamiltonian but sympy doesn't know this since at this point Zs are just arbitrary symbols not associated to any matrix. Note that there is big difference symbol is defined as Z or 1 - Z. If 1-Z is defined as a symbol then `sympy.expand` will just return the same expression, while if Z is the symbol then it will actually expand everything and express it as a sum of Z terms, which for this example is quite heavy.

I compared four different ways to define the Z symbol:
1. Using sympy directly: `z = sympy.symbols(" ".join((f"n{i}" for i in range(nqubits))))`
2. Creating a new symbol by inheriting sympy similarly to what we do in qibo:
```Python
class Symbol(sympy.Symbol):

    def __new__(cls, q, matrix=None, name="Symbol"):
        name = "{}{}".format(name, q)
        return super().__new__(cls=cls, name=name)

s = [(1 - Symbol(i)) / 2.0 for i in range(nqubits)]
```
3. Same as the above but using the `commutative=False` option, as we do in qibo (see [here](https://github.com/qiboteam/qibo/blob/30acf42d6ab8b1ca10c3ee6108ee34b91e4cdf9e/src/qibo/symbols.py#L6)):
```Python
class Symbol(sympy.Symbol):

    def __new__(cls, q, matrix=None, name="Symbol"):
        name = "{}{}".format(name, q)
        return super().__new__(cls=cls, name=name, commutative=False)
```
4. Using the `qibo.symbols.Symbol`.

and here are the results:

nqubits | sympy | custom symbol | non-commutative symbol | qibo symbol
-- | -- | -- | -- | --
5 | 0.01427 | 0.01456 | 0.01294 | 0.01470
6 | 0.02743 | 0.02837 | 0.02651 | 0.02915
7 | 0.05709 | 0.04961 | 0.06563 | 0.05388
8 | 0.11038 | 0.11466 | 0.11683 | 0.12667
9 | 0.21309 | 0.20427 | 0.24308 | 0.25024
10 | 0.41200 | 0.41907 | 0.51898 | 0.48970
11 | 0.79272 | 0.79048 | 0.99707 | 1.03600
12 | 1.64679 | 1.62807 | 2.18068 | 2.05435
13 | 3.41038 | 3.45738 | 4.15146 | 4.32526
14 | 6.66197 | 7.07146 | 9.59534 | 9.15934
15 | 12.69703 | 12.85655 | 18.13033 | 18.03427
16 | 27.18639 | 27.62989 | 37.51302 | 41.98114
17 | 62.53965 | 64.11467 | 84.81026 | 80.57820
18 | 118.92322 | 121.58077 | 168.88522 | 171.35654

from which I see the following:
* The biggest difference is caused by the `commutative=False` property. In the case of Z terms only this is useless but for Hamiltonians that mix different operators it is required since for example `X[0]Z[0]` is different than `Z[0]X[0]`.
* There is a smaller overhead associated with inheriting the `sympy.Symbol` and defining additional methods as the commutative custom symbol is slightly slower than sympy and qibo symbol is slightly slower than the non-commutative custom symbol.

**Comment by scarrazza** [comment]
@stavros11 thanks for these tests. I assume that the `sumpy` implementation uses `commutative=False` by default, correct? If that's true then for other Hamiltonians that mix different operators this approach will not hold, do you know how this flag deteriorates the `sympy` performance?

**Comment by stavros11** [comment]
> @stavros11 thanks for these tests. I assume that the `sumpy` implementation uses `commutative=False` by default, correct? 

Yes, that is correct, the default sympy choice is `commutative=True`, see for example [here](https://docs.sympy.org/latest/modules/core.html?highlight=symbol#id21). Another way to see this is the following example:
```Python
import sympy
z = sympy.symbols("z0 z1")
x = sympy.symbols("x0 x1", commutative=False)
print(z[0] * z[1] == z[0] * z[1]) # prints True
print(z[0] * z[1] == z[1] * z[0]) # prints True

> do you know how this flag deteriorates the `sympy` performance?

**Comment by stavros11** [comment]
> @stavros11 thanks for these tests. I assume that the `sumpy` implementation uses `commutative=False` by default, correct? 

Yes, that is correct, the default sympy choice is `commutative=True`, see for example [here](https://docs.sympy.org/latest/modules/core.html?highlight=symbol#id21). Another way to see this is the following example:
```Python
import sympy
z = sympy.symbols("z0 z1")
x = sympy.symbols("x0 x1", commutative=False)
print(z[0] * z[1] == z[0] * z[1]) # prints True
print(z[0] * z[1] == z[1] * z[0]) # prints True
print(x[0] * x[1] == x[0] * x[1]) # prints True
print(x[0] * x[1] == x[1] * x[0]) # prints False
```

> do you know how this flag deteriorates the `sympy` performance?

**Comment by stavros11** [comment]
Another approach we could take is to remove expand completely. Only removing the call does not work as the current parsing from symbols to the corresponding qibo Hamiltonian terms assumes that the sympy expression is expanded. But in principle we could think of a better way to do this parsing to avoid expanding. 

For example, for the Hamiltonian (1-Z1)^6(1-Z2)^6...(1-Zn)^6 that I used in the above example, if one needs to construct the dense matrix this can be done directly using matrix multiplications from this expression without expanding. The issues start when the user needs to trotterize, because for that we need to express the Hamiltonian as a sum of local terms. That being said, I am not sure if it makes sense to trotterize Hamiltonians such as this one since it contains n-qubit terms. If I am not mistaken trotterization is only useful for k-local Hamiltonians, mostly when k << n, as in this case we can exponentiate the 2^k matrix instead of the full 2^n.

**Comment by scarrazza** [comment]
Ok, then from your summary, I see two conditionals that we could have in the code:
- the possibility to decide a priori if the expression requires expansion.
- the necessity to allow commutation.

In principle we could start by having manual flags (function arguments) to control both options.

On the other hand, it sounds like both problems could be preprocessed automatically when the users passes the symbolic expressions. What do you think?
