### ISSUE TITLE
Usage of Gate.on_qubits() method

### ISSUE THREAD

**Issue by mlazzarin** [qiboteam/qibo#472]
Hi! I'm trying to understand how to use the ``qibo.abstractions.abstract_gates.Gate.on_qubits()`` method.
By reading the documentation, I understood that such method is used to obtain a gate that acts on some target qubits by cloning a gate that was originally created with different targets.

Indeed, in the following example it works
```python
from qibo.models import Circuit
from qibo import gates

c = Circuit(2)
gate = gates.H(0)
c.add(gate)
c.add(gate.on_qubits(1))
print(c().state())
```
but in this one it doesn't work
```python
from qibo.models import Circuit
from qibo import gates

c = Circuit(2)
gate = gates.H(1)
c.add(gate)
c.add(gate.on_qubits(0))
print(c().state())
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...qibo/src/qibo/abstractions/abstract_gates.py", line 214, in on_qubits
    gate = self.__class__(*qubits, **self.init_kwargs)
  File "...qibo/src/qibo/abstractions/abstract_gates.py", line 213, in <genexpr>
    qubits = (q[i] for i in self.qubits)
IndexError: tuple index out of range

```
Am I using the method properly?

**Comment by stavros11** [comment]
Thank you for reporting this. Indeed the documentation is misleading regarding this but I am not sure if I would call it a bug. I believe the `gate.on_qubits` method was not designed for direct usage but as a helper method for [`circuit.on_qubits`](https://github.com/qiboteam/qibo/blob/30acf42d6ab8b1ca10c3ee6108ee34b91e4cdf9e/src/qibo/abstractions/circuit.py#L154). This method was requested to allow adding smaller circuits to larger ones to ease the coding of quantum algorithms that are expressed via subroutines that are repeated and acting on different sets of qubits. You can check the issue #253 for more details.

Now regarding the current issue, I believe it never appears if `.on_qubits` is used at the level of circuits since the qubit numbering on circuits always starts from 0. For example:
```Python
smallc = models.Circuit(2)
smallc.add(gates.H(1))


largec = models.Circuit(3)
largec.add(smallc.on_qubits(0, 1))
```
works as expected.

A simple solution would be to keep `gate.on_qubits` for internal usage only, for example by renaming it `gate._on_qubits` which will also hide it from the docs, exposing only `circuit.on_qubits` to users. I believe `gate.on_qubits` is not useful on its own anyway, for example:
```Python
gate = gates.H(1)
c.add(gate.on_qubits(0))
```
would be equivalent to the simpler `c.add(gates.H(0))` and this is true for any gate. Let me know if you agree or I am missing some potential application of `gate.on_qubits` here.

**Comment by mlazzarin** [comment]
Ok, thank you for the answer. If I understand correctly, `len(q)` must be greater than the highest qubit id of the original gate, so that
```python
gates.CNOT(0, 1).on_qubits(2 ,3)
```
works,
```python
gates.CNOT(2, 3).on_qubits(0, 1)
```
does not, but
```python
gates.CNOT(2, 3).on_qubits(obj, obj, 0, 1, ...)
```
works. In `circuit.on_qubits` this condition is verified so there are no issues. I agree to keep it for internal usage only,  given that the standard way to add gates is simpler and less prone to errors (e.g. ``.on_qubits(*range(nqubits))`` does not change anything, but an unaware user may think that it "moves" the gate towards qubit 0).

**Comment by stavros11** [comment]
> ```python
> gates.CNOT(2, 3).on_qubits(obj, obj, 0, 1, ...)
> ```

Indeed as you can see from the source code of `gate.on_qubits` it will ignore all numbers in the given new list of qubits except the ones in the position of the original qubits (in this case 2, 3 as you correctly placed 0 and 1). If the given qubits is smaller you'll get the error. Obviously this behavior is confusing if exposed to users but I think it's the one that works well with `circuit.on_qubits` (I am not wrong). So if there are no other suggestions (eg. by @scarrazza) I believe renaming to `_on_qubits` is a good solution.

**Comment by mlazzarin** [comment]
> Would you like to make this update or shall I open a PR?

Ok, I'm on it.

**Comment by scarrazza** [comment]
Thanks for reporting this issue. I agree with the renaming, sounds reasonable at this point.

**Comment by igres26** [comment]
I also agree with the renaming. The `.on_qubits()` was designed to be used on Circuits to make building complex circuits with repeating parts a bit easier, so it makes sense to hide it from the gate methods.
