### ISSUE TITLE
implement doctests

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#483]
Following our discussion, we should test the code examples in docstrings.
One possibility is to use https://docs.python.org/3/library/doctest.html

**Comment by andrea-pasquale** [comment]
Of course, I will look into it.

**Comment by stavros11** [comment]
> where the line `print(c.draw())` is compared to the drawing of the circuit below when executing the code.

I guess the initial idea was to just check if the code cell works, eg. if it executes or raises any error but not necessarily check the output. This would be a good first step on this. If you can also check the output this would of course be even better but may be much harder to implement as you might find cases in the examples where we don't specify the output and even when we do there is no specific structure to where or how we specify.

> I ask this because in the case of tensors the output depends on the backend used, therefore the example in the docstring must specify correctly the backend and the printed tensor.

Generally in tests if you like to check whether two tensors agree you can use
```Python
from qibo import K
K.assert_allclose(final_tensor, target_tensor)
```
which should work for any backend and regardless of the types. For example `final_tensor` can be `tf.Tensor` while `target_tensor` is `np.ndarray` and this will still pass as long as they have the same shape and values. Following what I wrote above though, I am not sure if this can be incorporated above, for example if you want to compare printed tensors then that's a different story.

**Comment by mlazzarin** [comment]
If I understand correctly, in order to use the **doctest** library it is required to edit all examples in both the source code and the documentation itself.
I guess the rendered docs would also change as well.
It may be tedious, so I would suggest to implement such tests only for a small portion of the code, then maybe open a PR so that we can discuss if it's actually what we want or look for alternatives (maybe this https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html)

**Comment by mlazzarin** [comment]
Shall we close this issue?

**Comment by scarrazza** [comment]
Yes, lets close it now. Thanks.
