### ISSUE TITLE
Memory overhead

### ISSUE THREAD

**Issue by AdrianPerezSalinas** [qiboteam/qibo#541]
I am trying to allocate two 32-qubit circuits in single precision in a 96GB machine. Each vector should need 32GB, making a total of 64 GB, which should fit in memory. However, when the code is run a memory error is raised. Is there any reason why this happens?

**Comment by scarrazza** [comment]
Please share a minimal example which raises the memory issue.

**Comment by AdrianPerezSalinas** [comment]
```
from qibo.models import Circuit
from qibo import gates
import numpy as np

qubits = 30

C1 = Circuit(qubits)
for q in range(qubits):
    C1.add(gates.H(q))

state1 = C1.execute().numpy()

C2= Circuit(qubits)
for q in range(q):
    f = np.random.randint(2)
    if f == 0:
        C2.add(gates.X(q))
    

state2 = C2.execute(initial_state=state1.copy()).numpy()


overlap = np.conj(state1).dot(state2)  
print('Overlap is', overlap)

```

This is my script. The circuits are not exactly those, but the structure is.

**Comment by AdrianPerezSalinas** [comment]
If this is the standard behavior, I guess everything is fine. Somehow I expected the `.dot()` to not take much memory. Thanks!

**Comment by stavros11** [comment]
Indeed, I also tried to execute this in our machines and the memory usage is as expected. The qibo part allocates two state vectors for `state1` and `state2` while the overlap calculation allocates another one. I have not checked if the additional vector is allocated due to `np.conj` or the `.dot` operation.

@AdrianPerezSalinas, I believe the issue here is whether it is possible to calculate the overlap without creating an additional copy. This is not directly qibo related, but programmatically speaking it should be possible. If the numpy approach you are using is not doing this, a simple work aroundis to write a numba operator for the overlap calculation.
```Python
from numba import prange, njit

@njit(parallel=True)
def overlap(state1, state2):
    overlap = 0
    for i in prange(len(state1)):
        overlap += np.conj(state1[i]) * state2[i]
    return overlap
```
I tested this in your example and the total memory footprint (including overlap calculation) is only two state vectors, while performance is also acceptable if you compile with `parallel=True`. This should solve the memory issue.
