### ISSUE TITLE
how to define a new gate XX, YY, ZZ

### ISSUE THREAD

**Issue by ihpcdingwj** [qiboteam/qibo#591]
In order to transfer this code to qibo: circuit += [cirq.ZZ(*bits)**symbols[6]]
How do I define a new gate object ZZ?
is it using gates.Unitary(unitary, *q, trainable=True, name=None)
or other gates to follow the approach?

**Comment by ihpcdingwj** [comment]
here is how my solution: 
 matrixZZ = K.np.kron(matrices.Z,matrices.Z)
 c.add(symbols[6]*gates.Unitary(matrixZZ, 0, 1))

does it look ok?

**Comment by ihpcdingwj** [comment]
> > here is my solution: matrixZZ = K.np.kron(matrices.Z,matrices.Z) c.add(symbols[6]*gates.Unitary(matrixZZ, 0, 1))
> > does it look ok?
> 
> Yes, this should work. You can also use numpy directly to create the matrix:
> 
> ```python
> import numpy as np
> from qibo import matrices
> matrixZZ = np.kron(matrices.Z, matrices.Z)
> ```
> 
> What will probably not work is the multiplication between `symbols[6]` and the gate. What is `symbols[6]`? Is it a sympy.Symbol or a number?

symbols[6] here is a number. I am trying to code these two lines:
1. circuit += [cirq.ZZ(*bits)**symbols[6]]
2. pool_circuit.append(sink_circuit**-1)
There are ** operator in the both lines, on a gate and a circuit respectively.
What are the ** operations here mean?

**Comment by scarrazza** [comment]
@ihpcdingwj can we close this issue?

**Comment by stavros11** [comment]
@ihpcdingwj if you are still implementing this please merge the latest master to your branch and add the gates using the new layout. This should be simpler than before, you basically have to:
1. add the new gate classes to [qibo/gates/gates.py](https://github.com/qiboteam/qibo/blob/master/src/qibo/gates/gates.py). You can use the gates that are already there as a template.
2. add the gate matrices as numpy arrays to [qibo/backends/matrices.py](https://github.com/qiboteam/qibo/blob/master/src/qibo/backends/matrices.py).

Let us know if you have any issues.

**Comment by damarkian** [comment]
I took some liberties and added Rxx, Ryy, Rzz gates as how @stavros11 recommended. To get the XX, YY and ZZ gates, the parameter would have to be specified as pi/2. 

All in rnn branch: https://github.com/qiboteam/qibo/commit/a3f52f2577160fc8f1f09a88cd13b7eb42f02a27

Is this ok?

**Comment by stavros11** [comment]
> Is this ok?

Thanks @damarkian. Yes, it looks perfect to me. If you can also add some tests for these gates similarly to [here](https://github.com/qiboteam/qibo/blob/1af034218bb34871294aa7ac6d34b3694856444c/src/qibo/tests/test_gates_gates.py#L103), then please open a PR so that we can merge this to master for everyone to use.

**Comment by damarkian** [comment]
The test_rz -> test_rzz couldn't be replicated directly, so I wrote my own test_rzz with similar logic. 

Otherwise, rxx and ryy are similar to rx and ry tests, respectively.

[Here](https://github.com/qiboteam/qibo/blob/a75ab7a2c4e11d4aa56b793b85886cbaccce0020/src/qibo/tests/test_gates_gates.py#L280).

**Comment by stavros11** [comment]
@damarkian thanks. The tests look good to me, please open a PR so that we can review and merge. There is no need to implement any other features, only the new gates and tests. Then you can continue with other developments in a different branch on top of this.

You may have noticed that there is an issue with tests in GitHub's CI. This is not related to your work and we will fix separately.
