### ISSUE TITLE
Whitespace in c.draw()

### ISSUE THREAD

**Issue by JoexGibbs** [qiboteam/qibo#645]
When using the circuit draw function, I am finding the visual representation is not moving commuting gates leftwards, which is unnecessarily creating much wider circuits than necessary.

e.g.

```
n=8  
c = Circuit(n)
for i in range(0, n-1, 2):
    c.add(gates.CNOT(i, (i+1)%n))
    c.add(gates.RZ((i+1)%n, theta=0))
    c.add(gates.CNOT(i, (i+1)%n))
    
  for i in range(1, n-1, 2):
    c.add(gates.CNOT(i, (i+1)%n))
    c.add(gates.RZ((i+1)%n, theta=0))
    c.add(gates.CNOT(i, (i+1)%n))

  print(c.draw())

```
Produces the image:

<img width="394" alt="image" src="https://user-images.githubusercontent.com/109437810/191448101-8cd1c937-2140-441e-bca0-9a444ec22d81.png">

This should show a neat brickwork circuit, yet has lots of 'whitespace', and seems an inefficient use of screen space.
Could this be improved?

**Comment by stavros11** [comment]
Thanks for reporting this. You are right. 

This happens because in `circuit.draw()` we are looping through the gate queue, which contains the gates in the order added by the user. It should be possible to get the "brickwork" circuit if we instead loop through `queue.moments`. I can have a look on this unless someone else wants to help as it should be simple to fix.

@scarrazza this is a toy example of how the gate parallelization can be implemented using the moments.

**Comment by scarrazza** [comment]
Indeed, we should use moments for drawing too.

**Comment by scarrazza** [comment]
We have discussed about this point recently. This choice of spacing is intentional to avoid the introduction of new symbols which would make the draw too dense. The current setup uses more space but provides a cleaner representation for small sized circuits.
