### ISSUE TITLE
Quantum Fisher Information Matrix

### ISSUE THREAD

**Issue by DiegoGM91** [qiboteam/qibo#657]
I think it would be useful to incorporate the computation of the Quantum Fisher Information Matrix (QFIM) in `qibo`. The QFIM is defined for parametrized (i.e. variational) quantum circuits, and it quantifies the distance traveled in Hilbert space for small variations of the variational parameters. Its rank is equal to the number of orthogonal directions that the circuit can have access to in Hilbert space.

Here is a lovely review about the QFIM: https://arxiv.org/abs/2103.15191

I already have a code that computes the QFIM, from a previous project, so I can try to give it a go.

But maybe a discussion with @scarrazza and @stavros11 would be useful for me before that.

**Comment by renatomello** [comment]
Adding to this, I think Qibo could have a module like Qiskit's [quantum_info](https://qiskit.org/documentation/apidoc/quantum_info.html) with several useful measures and operators, and the QFIM would fit in the module IMO.

**Comment by scarrazza** [comment]
We have discussed this issue yesterday and we fully agree, Diego will have a go for QFIM.

**Comment by renatomello** [comment]
I (with @stavros11 major help) already have a few things up and running w.r.t. Pauli basis and operators. It could be added to the module. Also, I could have a go for the measures.

**Comment by scarrazza** [comment]
Great, @renatomello could you please coordinate this effort with @DiegoGM91 and @stavros11?

**Comment by renatomello** [comment]
> Great, @renatomello could you please coordinate this effort with @DiegoGM91 and @stavros11?

Sure

**Comment by stavros11** [comment]
We were discussing earlier with @DiegoGM91 and apparently the Fisher Information Matrix is calculated using the parameter shift rule. Given that this is a very useful tool for people working with variational circuits, I believe it would make sense to first implement this in qibo and then base the Fisher Information on top of it. @MatteoRobbiati already implemented the parameter shift in #654, but this is only an example that is not part of the main code. We should consider moving parts of this example to qibo core.

The main points during our discussion today:
* We should think of what would be a good API for the parameter shift from the user perspective. For example it could be a circuit method, but we are not sure as it also requires a loss. @DiegoGM91 may give a try to sketch something for this.
* Fisher Information requires second order parameter shift and is not clear if we can have a flexible enough implementation that accommodates different orders.
* The implementation may should be backend dependent and act differently on hardware and simulation. For example in simulation we can use tricks like caching to potentially speed up the calculation. Such tricks are not possible on hardware. The front API should be unique, though, so that the same code runs with all backends (like `circuit.execute`).

**Comment by renatomello** [comment]
@DiegoGM91 if it still interests you, this was finally implemented and recently merged.
