### ISSUE TITLE
Fuse of inverse of multiple gates gives multiple gates 

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibo#676]
When building the inverse gate of all gates in a circuit, the gates are not fused but applied one by one, meaning they are not fused.
This is problematic for simulating noise for example.
``` python
from qibo import models, gates
circuit = models.Circuit(1)
circuit.add(gates.H(0))
circuit.add(gates.X(0))
inverse = circuit.invert().fuse().queue[0]
circuit.add(inverse)
print(circuit.draw()) # q0: ─H─X─X─H─
```
Right now, the single fused inverse gate has to be build by hand.
``` python
from qibo import models, gates
circuit = models.Circuit(1)
circuit.add(gates.H(0))
circuit.add(gates.X(0))
inverse = circuit.invert().fuse().queue[0]
circuit.add(gates.Unitary(inverse.matrix,0))
print(circuit.draw()) # q0: ─H─X─U─
```

**Comment by stavros11** [comment]
Thanks for opening this. Fused gates hold the collection of gates to be fused, but the actual matrix (=fusion of gates) is calculated only if you execute the circuit containing the fused gates. Also `circuit.add` accepts iterators, for example you can do things like:
```py
circuit.add(gates.H(i) for i in range(5))
```
If you add the fused gate in a circuit it will be treated as an iterator instead of a single gate, that's why you are getting this.

Using the `Unitary` approach is not necessarily bad, because you are explicitly saying that you want to add a single gate. However, if you would prefer to add the `FusedGate` directly, I think the easiest way to fix it would be to modify `circuit.add` to treat it as single gate instead of iterators.

By the way, another way to invert the whole circuit is to construct its unitary using `circuit.unitary()` and then add the dagger of this as a `Unitary` gate. This will be more robust if you have more than one qubit because gate fusion uses `max_qubits=2` by default.
