### ISSUE TITLE
Deploy test failing

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#748]
Doc deployment tests are failing.

**Comment by AleCandido** [comment]
The reason is clearly written in the logs:
https://github.com/qiboteam/qibo/actions/runs/3794582109/jobs/6452832425#step:2:28

You need to enable the deployment from actions, that is not the default (that is deploying from branch).

The link to change the option is provided in the docs, it involves changing one repo setting, but I can't do it myself.

**Comment by scarrazza** [comment]
Thanks, works.
