### ISSUE TITLE
Stable documentation issue

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibo#754]
There is an issue with deployment for stable releases, after tagging v0.1.10 we get:
- v0.1.10.dev0 in https://qibo.science/docs/qibo/stable instead of v0.1.10
- v0.1.11.dev0 in https://qibo.science/docs/qibo/latest

**Comment by scarrazza** [comment]
By looking at the fonts, I guess there is some link url update missing.

**Comment by AleCandido** [comment]
The error is in the workflow: it is always falling in this [branch of the `if`](https://github.com/qiboteam/workflows/blob/67e62f8a65caa6cfb6cd51c25c31ee544ef2eed3/.github/workflows/deploy-ghpages-latest-stable.yml#L99)
```
            cp -a "${label}"/. "${missing_doc}"
```
So the two versions are always the same, and they have been overwritten by the new run (not 100% sure, but 90% yes, since there is no log from the `tar` command, but `-v` is not passed).

**Comment by scarrazza** [comment]
Why the stable is using ubuntu font while the latest furo?

**Comment by AleCandido** [comment]
The developer is on holiday, please contact the other maintainers (or wait until tomorrow) :P

**Comment by Edoardo-Pedicillo** [comment]
Looking at the log, the if branch seems to work because the `wget` always exits with a true status, furthermore the two docs are different, which means that the copy step was not performed (as @AleCandido suggests, I agree to add the verbose option). I suppose the issue comes from the fact that the last workflow was launched one minute after the previous one. I tried with a forked Qibo repository to create a new tag and I had the same issue. Since the artifact was generated correctly but the github-pages were not updated, when I changed the version in the main branch a few minutes later, I do not see what I expected. I solved the problem, repeating the entire process and waiting for the webpage's update. I re-runned the [workflow](https://github.com/qiboteam/qibo/actions/runs/3805994485), and now the website is working correctly.

**Comment by scarrazza** [comment]
Thanks @Edoardo-Pedicillo.

**Comment by AleCandido** [comment]
I'm glad you managed to solve, so we can consider it fine :)

However, I'm still puzzled about this result:
https://github.com/qiboteam/qibo/suites/10110527801/artifacts/493177549
i.e. the artifact generated by the run on the tag v0.1.10, since the version in both latest and stable is without the "dev". For sure latest online had the "dev" in the version, so it can't be generated by untaring the result of wget.
But if it's not reproducible it is rather impossible to debug, so if now it's working, so much the better (it might also be the result of a network issue, verbose logs will help us if it will ever happen again).
