### ISSUE TITLE
Qibocal tests fail

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibo#831]
With the new `Qibo` version, some `Qibocal`'s tests [fail ](https://github.com/qiboteam/qibocal/actions/runs/4435222779/jobs/7782115441#step:10:26)( here the installed [version](https://github.com/qiboteam/qibocal/actions/runs/4435222779/jobs/7782115441#step:6:57) ).

**Comment by stavros11** [comment]
Here is a minimal example that I believe reproduces this issue
```py
from qibo import gates
from qibo.models import Circuit
from copy import deepcopy


c = Circuit(1)
gate = gates.M(0)
c.add(gate)
cgate = deepcopy(gate)
```
Particularly the issue appears when one tries to `deepcopy` a measurement gate object after it has been added to a circuit. Note that it is not related to `circuit.copy`, it appears because qibocal is using a custom function to perform the circuit copy:

https://github.com/qiboteam/qibocal/blob/37a6424c16c1fdb00cbd610152f4e1eeff77519c/src/qibocal/calibrations/niGSC/basics/utils.py#L86

I am having a look on what is causing the issue with the `deepcopy`. In the meantime, in may be worth replacing the custom copy in qibocal to `circuit.copy(deep=True)` which I believe does the same, to avoid code repetition between the two libraries.
