### ISSUE TITLE
Error loading data in examples

### ISSUE THREAD

**Issue by Simone-Bordoni** [qiboteam/qibo#948]
In some examples where it is necessary to load data from a different folder the code is not running.

I have found this problem in:
anomaly_detection
variational_classifier

**Comment by Simone-Bordoni** [comment]
I made an error as i was not executing the file from the correct folder. However as @AleCandido suggested it should be better to have an absolute path to get the data.

**Comment by AleCandido** [comment]
I.e. you should get them relatively to the file path.

In particular, `__file__` is a special variable containing the path of the module (filled by Python itself during the load process), so it's customary to do something like:
```py
from pathlib import Path

here = Path(__file__).parent
```

Once you have the directory containing the example in the `here` variable, you could use that one to spell out the path to the data.
E.g. 
```py
here / "parameters" / "trained_params.npy"
```
instead of:
https://github.com/qiboteam/qibo/blob/d914f0c1e9487f5ef84aeb1b541bdc6479412978/examples/anomaly_detection/test.py#L184

**Comment by scarrazza** [comment]
@Simone-Bordoni could you please implement this change in your example and in the other examples with similar issues?

**Comment by Simone-Bordoni** [comment]
I have changed them in PR #947 
I have updated anomaly detection and variational classifier, moreover i have eliminated and unuseful import from EFQAE
